config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  authenticated :user do
    resources 'users'
    resources 'users' do
      member do
        get 'user_friends'
      end
    end
    resources 'friendships',  only: [:create, :update, :destroy]
    resources 'posts',        only: [:create, :destroy]
    resources 'likes',        only: [:create, :destroy]
    resources 'comments',     only: [:create, :destroy]
    root to: 'users#current_user_home', as: :authenticated_root
  end

  resources 'posts', only: [:index]
  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true, length: { minimum: 2, maximum: 140 }
  belongs_to :user
  belongs_to :post

  default_scope -> { order(created_at: :desc) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.build(comment_params)

    if @comment.save
      flash[:notice] = "Comment saved!"
    else
      flash[:alert] = "Something went wrong!"
    end
    redirect_to posts_path
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])

    if @comment.destroy
      flash[:notice] = "Comment deleted!"
    else
      flash[:alert] = "Something went wrong!"
    end
    redirect_to posts_path
  end

  private
    def comment_params
      params.require(:comment).permit(:post_id, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li>
  <% post.comments.each do |c| %>
    <span class="content"><%= c.content %>
      <!-- this block allows liking/unliking comments -->
      <% unless c.content.nil? %>
        <%= render 'shared/like_stub', post: c %>
      <% end %>
      <!-- if weird stuff happens when liking comments, remove/retool this -->
    </span>
    <span class="info">
      <% unless c.user.nil? && c.created_at.blank? %>
        <%= link_to gravatar_for(post.user, size: 20), post.user %>
        <%= "Posted #{time_ago_in_words(c.created_at)} ago by #{c.user.email}" %>
      <% end %>
      <br />
    </span>
    <% if current_user.comments.include?(c) || current_user.posts.include?(post) %>
      <span class="options">
        <ul>
          <li>
            <% unless c.id.nil? %>
              <%= link_to "delete comment", comment_path(c.id), method: :delete,
                                            class: "btn btn-xs btn-danger",
                                            data: { confirm: "Delete comment?" } %>
            <% end %>
          </li>
        </ul>
      </span>
    <% end %>
  <% end %>
</li>

app/views/comments/_comment_form.html.erb
<%= form_for post.comments.new do |f| %>
  <div class="field">
    <%= f.hidden_field :post_id %>
    <%= f.text_area :content, placeholder: "New comment here" %>
  </div>
  <%= f.submit "Post comment", class: "btn btn-primary btn-sm" %>
<% end %>