config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  authenticated :user do
    resources 'users'
    resources 'users' do
      member do
        get 'user_friends'
      end
    end
    resources 'friendships',  only: [:create, :update, :destroy]
    resources 'posts',        only: [:create, :destroy]
    resources 'likes',        only: [:create, :destroy]
    resources 'comments',     only: [:create, :destroy]
    root to: 'users#current_user_home', as: :authenticated_root
  end

  resources 'posts', only: [:index]
  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div id="user_nav">
    <% if user_signed_in? %>
      Signed in as <%= current_user.email %>. Not you?
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> or
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>
    <small>
      <a href="http://www.theodinproject.com/ruby-on-rails/final-project?ref=lc-pb">
      Odin Facebook</a> at <a href="http://www.theodinproject.com">The Odin
      Project</a>
    </small>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Odin Facebook", root_path, class: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-left">
        <% if user_signed_in? %>
          <li>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <% if current_user.received_requests.count > 0 %>
                <span class="glyphicon glyphicon-heart" style="color:red"></span>
              <% else %>
                <span class="glyphicon glyphicon-heart" style="color:blue"></span>
              <% end %>
              <span class="badge"><%= current_user.received_requests.count %></span>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu navbar-inverse" role="menu">
              <% current_user.received_requests.each do |u| %>
                <li><%= render 'users/user', user: u %></li>
                <li class="divider"></li>
              <% end %>
            </ul>
          </li>
          <li><%= link_to "Friends", user_friends_user_path(current_user) %></li>
          <li><%= link_to "Timeline",         posts_path %></li>
          <li><%= link_to "Browse all users", users_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",     root_path %></li>
        <li><%= link_to "Help",     help_path %></li>
        <li><%= link_to "About",    about_path %></li>
        <li><%= link_to "Contact",  contact_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, message| %>
  <% if message.is_a?(String) %>
    <%= content_tag :div, message, class: "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Odin Facebook | <%= find_title(yield(:title), "Facebook for Odin") %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>